apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qp4d00z6y-java-quarkus
  janus-idp.io/tekton: qp4d00z6y-java-quarkus
  backstage.io/kubernetes-id: qp4d00z6y-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qp4d00z6y-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
